### ISSUE TITLE
persistence.storagePid scheint nicht so zu funktionieren wie gewünscht

### ISSUE THREAD

**Issue by X-Tender** [plobacher/extbasebookexample#1]
Ich bin in dem Buch bei dem Teil wo man die Tags implementiert.
Dabei ist mir aufgefallen das meine Posts nicht in den Storage für die Posts landen sondern in dem von den Blogs.

Der Initiale Code aus dem Buch ist (Ids an meine Struktur wurde angepasst):
```
persistence {
	storagePid = 3
	recursive = 1
	classes = {
		Pluswerk\Simpleblog\Domain\Model\Blog {
			newRecordStoragePid = 4
		}
		Pluswerk\Simpleblog\Domain\Model\Post {
			newRecordStoragePid = 5
		}
		Pluswerk\Simpleblog\Domain\Model\Comment {
			newRecordStoragePid = 6
		}
		Pluswerk\Simpleblog\Domain\Model\Tag {
			newRecordStoragePid = 7
		}
	}
}
```

nachdem ich hier im repository geschaut habe habe ich es dann so umgabaut:
```
persistence {
	storagePid = 0,4,5,6,7
	classes = {
		Pluswerk\Simpleblog\Domain\Model\Blog {
			newRecordStoragePid = 4
		}
		Pluswerk\Simpleblog\Domain\Model\Post {
			newRecordStoragePid = 5
		}
		Pluswerk\Simpleblog\Domain\Model\Comment {
			newRecordStoragePid = 6
		}
		Pluswerk\Simpleblog\Domain\Model\Tag {
			newRecordStoragePid = 7
		}
	}
}
```

Jetzt landet alles im absolutem root mit der ID 0.
Was mache ich Falsch, oder ist es ein neuer typo3 Bug.
typo3 7.6.16

**Comment by plobacher** [comment]
Hi, lass mal das = nach classes weg - also nur: 

classes {

dann müsste es gehen :-)

Liebe Grüße
Patrick

**Comment by X-Tender** [comment]
Oweh. Da habe ich wohl den Wald vor lauter Bäume nicht gesehen. Danke
hierfür und für das großartige Buch.

Patrick Lobacher <notifications@github.com> schrieb am Fr., 3. März 2017,
06:59:

**Comment by X-Tender** [comment]
Funktioniert.
Auch mit recursive = 1:)
