### ISSUE TITLE
Unverständliche Textpassage

### ISSUE THREAD

**Issue by X-Tender** [plobacher/extbasebookexample#2]
Kapitel 14.1 steht im letzten Abschnitt:

> Im Kapitel [Konfiguration via TyposScript und Flexforms]{#chapter050namespace} haben wir [..]`

ÄÄh bitte wo? Klar "Konfiguration via TyposScript und Flexforms" finde ich aber dat andere? :)
Worauf bezieht sich also der Verweis. :)

**Comment by plobacher** [comment]
Das ist eigentlich ein interner Verweis auf eine Stelle im Kapitel "TypoScript & Flexforms" und zwar zur Stelle: "Auf diese Weise könnte man z.B. einen Standard-Namespace zu allen Fluid-Templates hinzufügen...."

**Comment by X-Tender** [comment]
Danke. Habs gefunden.
