### ISSUE TITLE
Konfiguration via Typoscript und Flexforms

### ISSUE THREAD

**Issue by matthaeus-dauskonzept** [plobacher/extbasebookexample#7]
Hallo,

ich habe gerade das Kapitel 11 "Konfiguration via Typoscript und Flexforms" beendet und seit ich versucht habe ein SCA einzubinden funktionieren "SHOW", "EDIT" und "DEL" nicht mehr und rooten mich konsequent auf 404. Ich weiß leider nicht woran das liegt, ich habe sogar in meiner Verzweiflung schon den hier hinterlegten Code in meine Dateien kopiert, leider erfolglos. Woran kann das liegen? könnte es damit zu tun haben, dass ich in TYPO3 v8.7 entwickle?

Vielen Dank, Beste Grüße,
Matthäus

**Comment by Footrotflat** [comment]
Hallo Matthäus

Es gibt ja mehrere Möglichkeiten das SCA einzubinden,
Ich beschreibe dir die Variante, als Datei in der Configuration.

Verzeichnisbaum:
DeineExtension/Configuration/FlexForms

Hier speicherst du die Datei z.B.:
Main.xml
Der Dateiname kannst du frei wählen.

Der Code für das SCA sieht grundlegend so aus:
Siehe Datei Main.txt
[Main.txt](https://github.com/plobacher/extbasebookexample/files/1928862/Main.txt)
(Dateiendung muss .xml sein!)

Das Plugin definierst du als Content irgendwo auf einer Webseite.
Im Plugin definierst du, welche Definition (im Beispiel: NAME 01, NAME 02) du in deinem Plugin haben möchtest.

SCA macht ja Sinn,
1. wenn du im Plugin nicht mit listAction beginnen möchtest, sondern z.B. mit newAction (siehe Definition NAME 02). Standard mässig beginnt die Ausgabe ja mit der listAction!
2. wenn du in einem Plugin z.B. die listAction nicht zugänglich machen möchtest.
Wenn du jetzt also im Plugin die Definition 'NAME 02' verwendest, kannst du auf der Webseite mit diesem Plugin die listAction und die showAction nicht mehr aufrufen! (Macht nicht unbedingt Sinn...!)

Nach der Definition immer schön den Cash leeren!
Wenn du im SCA in FlexForm eine Änderung gemacht hast, immer Plugin aufrufen und die Definition nochmals speichern und Cash leeren!

Wenn du damt nicht zurecht kommst, wäre es sinnvoll, wenn du dein Code zeigst.
(sonst ist es schwer zu helfen)   ;-)

Gruss Footrotflat

**Comment by Footrotflat** [comment]
...ach ja, an v 8.7 liegt es nicht.
Ich verwende 8.7.9 und es funktioniert.

Gruss Footrotflat

**Comment by matthaeus-dauskonzept** [comment]
Hallo Footrotflat,

vielen Dank nochmal für deine Hilfe. Es war zwar nicht genau, mein Problem, aber mein Problem hat sich nun aber auch erübrigt. Beim letzten Mal hatte ich die Übungs-Extension in ein bestehendes Projekt eingebaut, das mit der Übung überhaupt nichts zu tun hatte. Nachdem ich an dieser Stelle nicht weiter gekommen war, habe ich beschlossen, die Übung abzubrechen und in einer eigenen Übungs-Installation neu zu beginnen.
So geschehen und das Problem ist nicht wieder aufgetaucht. Ich bin jetzt an der Stelle, wo mir mein Problem aufgetaucht war und alles läuft wie beschrieben. Ich werde mich aber bestimmt nochmal Melden, wenn ich auf das nächste Problem stoße, und dann kann ich auch meinen Code zeigen :-)

Beste Grüße,

Matthäus

**Comment by Footrotflat** [comment]
Freut mich, dass du jetzt eine gute Lösung hast.
Gruss Footrotflat
